# Generated by Django 3.2.13 on 2022-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionarchive',
            name='quantity_after',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
