# Generated by Django 3.2.9 on 2022-07-02 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionarchive_quantity_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionarchive',
            name='who',
            field=models.CharField(default=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=64),
        ),
    ]
